# Generated by Django 4.2.9 on 2024-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='experience_required',
            field=models.IntegerField(default=10),
        ),
    ]
