# Generated by Django 4.2.9 on 2024-02-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskboard', '0003_projectboard_creator_subtask_creator_task_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_task', models.BooleanField(default=False)),
                ('can_add_subtask', models.BooleanField(default=False)),
                ('project_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.projectboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project_board')},
            },
        ),
    ]
