# Generated by Django 4.2.9 on 2024-02-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0004_taskpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
