# Generated by Django 4.2.9 on 2024-02-11 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskboard', '0006_subtask_completed_by_alter_subtask_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preparation'), (2, 'Ready'), (3, 'In Progress'), (4, 'Completed')], default=2),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Preparation'), (2, 'Ready'), (3, 'In Progress'), (4, 'Completed')], default=1),
        ),
    ]
