# Generated by Django 4.2.9 on 2024-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskboard', '0007_subtask_assigned_to_subtask_status_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (1, 'Medium'), (1, 'High'), (4, 'Immediate')], default=1),
        ),
    ]
