# Generated by Django 4.2.9 on 2024-07-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskboard', '0008_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Immediate')], default=1),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Member')], default=1)),
                ('project_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskboard.projectboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectboard',
            name='members',
            field=models.ManyToManyField(related_name='project_members', through='taskboard.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
