name: Django CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Ustaw Pythona
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'

    - name: Instalacja zależności
      run: |
        pip install -r requirements.txt

    - name: Run test
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
